services:
  - type: web
    name: sheep-sales-system
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./frontend/src
    envVars:
      - key: NODE_VERSION
        value: 18.12.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
